export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

// users
export const LOAD_USERS = "LOAD_USERS";

// device
export const LOAD_DEVICES = "LOAD_DEVICES";
export const CREATE_DEVICE = "CREATE_DEVICE";
export const UPDATE_DEVICE = "UPDATE_DEVICE";
export const REMOVE_DEVICE = "REMOVE_DEVICE";

// telemetries
export const LOAD_TELEMETRIES = "LOAD_TELEMETRIES";
export const UPDATE_TELEMETRIES = "UPDATE_TELEMETRIES";
export const LOAD_LATEST_TELEMETRIES = "LOAD_LATEST_TELEMETRIES";

// customer
export const LOAD_CUSTOMERS = "LOAD_CUSTOMERS";
export const CREATE_CUSTOMER = "CREATE_CUSTOMER";
export const UPDATE_CUSTOMER = "UPDATE_CUSTOMER";
export const REMOVE_CUSTOMER = "REMOVE_CUSTOMER";

// tenant
export const LOAD_TENANTS = "LOAD_TENANTS";
export const CREATE_TENANT = "CREATE_TENANT";
export const UPDATE_TENANT = "UPDATE_TENANT";
export const REMOVE_TENANT = "REMOVE_TENANT";

// widgetsBundle
export const LOAD_WIDGETS_BUNDLES = "LOAD_WIDGETS_BUNDLES";
export const CREATE_WIDGETS_BUNDLE = "CREATE_WIDGETS_BUNDLE";
export const UPDATE_WIDGETS_BUNDLE = "UPDATE_WIDGETS_BUNDLE";
export const REMOVE_WIDGETS_BUNDLE = "REMOVE_WIDGETS_BUNDLE";

// widgetType
export const LOAD_WIDGET_TYPES = "LOAD_WIDGET_TYPES";

// ruleChain
export const LOAD_RULE_CHAINS = "LOAD_RULE_CHAINS";
export const CREATE_RULE_CHAIN = "CREATE_RULE_CHAIN";
export const OPEN_RULE_NODES = "OPEN_RULE_NODES";
export const LOAD_RULE_NODE_DESCRIPTORS = "LOAD_RULE_NODE_DESCRIPTORS";
export const REMOVE_RULE_CHAIN = "REMOVE_RULE_CHAIN";

// dashboard
export const LOAD_DASHBOARDS = "LOAD_DASHBOARDS";
export const CREATE_DASHBOARD = "CREATE_DASHBOARD";
export const UPDATE_DASHBOARD = "UPDATE_DASHBOARD";
export const REMOVE_DASHBOARD = "REMOVE_DASHBOARD";
export const OPEN_DASHBOARD = "OPEN_DASHBOARD";
export const SAVE_CHANGES_DASHBOARD = "SAVE_CHANGES_DASHBOARD";

// alarms
export const LOAD_ALARMS = "LOAD_ALARMS";
export const UPDATE_ALARMS = "UPDATE_ALARMS";

// simulator device
export const LOAD_SIMULATOR_DEVICES = "LOAD_SIMULATOR_DEVICES";
export const CREATE_SIMULATOR_DEVICE = "CREATE_SIMULATOR_DEVICE";
export const UPDATE_SIMULATOR_DEVICE = "UPDATE_SIMULATOR_DEVICE";
export const REMOVE_SIMULATOR_DEVICE = "REMOVE_SIMULATOR_DEVICE";
