package com.iot.server.application.message;

public enum ActorMsgType {
  RULE_ENGINE_TO_RULE_CHAIN_MSG,
  RULE_CHAIN_TO_RULE_NODE_MSG,
  RULE_NODE_TO_RULE_CHAIN_MSG,
  RULE_CHAIN_TO_RULE_CHAIN_MSG,
  RULE_ENGINE_TO_RULE_CHAIN_UPDATE_MSG,
  RULE_CHAIN_TO_RULE_NODE_UPDATE_MSG,
  DELETE_ACTOR_MSG,
}
